server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.199.55.96:3306/wxdisdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: wxdis
    password: wxdis
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  mvc:
    view:
      prefix: /templates
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5

pagehelper:
  auto-dialect: mysql
  reasonable: true
  row-bounds-with-count: true
  offset-as-page-num: true
  params: count
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.wx.disparent.mallparent.entity
#指定日志 路径
logging:
  config: classpath:logback.xml
  file:
    path: D:\logs